Repository Foacs/ribz, pull requests merged in 2021-02, with the labels that each got.

#12 GENERATE JAVADOC & EXPORT IT
  .travis.yml
  LISEZMOI.md
  README.md
  build.gradle
  core/src/main/java/fr/foacs/ribz/core/BoardGame.java
  core/src/main/java/fr/foacs/ribz/core/controllers/CameraInputProcessor.java
  core/src/main/java/fr/foacs/ribz/core/screens/AbstractScreen.java
Labels: Priority: Low, Status: Review needed, Type: Maintenance

#18 FIX CI ISSUE WITH SONAR
  .travis.yml
  backend-api/build.gradle
  backend-impl/build.gradle
  build.gradle
  core/build.gradle
  desktop/build.gradle
  desktop/src/test/resources/log4j2-test.xml
  event-controller/build.gradle
  frontend-api/build.gradle
  frontend-impl/build.gradle
Labels: Priority: Critical, Type: CI

#19 FIX SONAR CODE SMELLS
  .gitignore
  .idea/sonarlint-state.xml
  .idea/sonarlint.xml
  core/src/main/java/fr/foacs/ribz/core/event/handler/MessageHandler.java
  event-controller/src/main/java/fr/foacs/ribz/event/controller/events/Event.java
  event-controller/src/main/java/fr/foacs/ribz/event/controller/handlers/EventHandler.java
  frontend-impl/src/main/java/fr/foacs/ribz/frontend/impl/manager/EntitiesManager.java
  response-controller/src/main/java/fr/foacs/ribz/response/controller/handlers/ResponseHandler.java
  response-controller/src/main/java/fr/foacs/ribz/response/controller/responses/Response.java
Labels: Priority: Low, Type: Refactoring

#21 VERSION 0.2-SNAPSHOT
  build.gradle
Labels: Type: Maintenance

#23 FIX UNIT TESTS FAILING ON WINDOWS
  frontend-impl/src/test/java/fr/foacs/ribz/frontend/impl/controllers/CameraInputProcessorTest.java
Labels: Type: Bug
